### ISSUE TITLE
v4 : Can't login to vCloudDirector

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvcloud#12]
i update to the last version v4. I update my code using new API : 

```python
def test_lib():
    vca = vcloudair.VCA(host, user, service_type='ondemand', version='5.1', verify=True)
    # vca.login(host, '%s@%s' % (user, org), password, None, 'vcd', '5.1')
    result = vca.login(password, org)
    print("Result: %s" % result)
```

Now, i can't log into my vCloudDirector account : 

```bash
./test.py 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.vcloud.com
send: 'GET /api/sc/instances HTTP/1.1\r\nHost: api.vcloud.com\r\nConnection: keep-alive\r\nAuthorization: Bearer FCA_OAB01\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json;version=5.1\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-30-generic\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Date: Tue, 10 Feb 2015 14:41:15 GMT
header: Content-Type: application/vnd.vmware.vcloud.error+xml;version=5.1
header: Date: Tue, 10 Feb 2015 14:41:15 GMT
header: Connection: close
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/sc/instances HTTP/1.1" 403 None
Traceback (most recent call last):
  File "./test.py", line 193, in <module>
    test_lib()
  File "./test.py", line 153, in test_lib
    result = vca.login(password, org)
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 88, in login
    self.instances = self.get_instances()
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 139, in get_instances
    if response.history[-1]:
IndexError: list index out of range
```

**Comment by pacogomez** [comment]
if the service type is OnDemand, you need to specify version 5.7

**Comment by nlamirault** [comment]
I try : 

```python
def test_lib():
    vca = vcloudair.VCA(host, user) # , service_type='ondemand', version='5.1', verify=True)                                                                                                                      
    # vca.login(host, '%s@%s' % (user, org), password, None, 'vcd', '5.1')
    result = vca.login(password, org)
    print("Result: %s" % result)

```

and the logs : 

```bash
./test.py
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.vcloud.com
send: 'GET /api/sc/instances HTTP/1.1\r\nHost: api.vcloud.com\r\nConnection: keep-alive\r\nAuthorization: Bearer FCA_OAB01\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json;version=5.7\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-30-generic\r\n\r\n'
reply: 'HTTP/1.1 406 Not Acceptable\r\n'
header: Date: Wed, 11 Feb 2015 13:27:59 GMT
header: Content-Type: application/json;version=5.7
header: Date: Wed, 11 Feb 2015 13:27:59 GMT
header: Connection: close
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/sc/instances HTTP/1.1" 406 None
Traceback (most recent call last):
  File "./test.py", line 193, in <module>
    test_lib()
  File "./test.py", line 153, in test_lib
    result = vca.login(password, org)
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 88, in login
    self.instances = self.get_instances()
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 139, in get_instances
    if response.history[-1]:
IndexError: list index out of range

```

**Comment by nlamirault** [comment]
Sorry for noise. Reading exemple it works.
