### ISSUE TITLE
Issue with vca-cli or pyvcloud

### ISSUE THREAD

**Issue by achirko** [vmware/pyvcloud#17]
Issue:
$ vca login -p <pw> -t subscription <user> --host https://vchs.vmware.com -v 5.6
Login successful for profile 'default'
$ vca org use --org <org> --service <service>
Using organization <org> in profile 'default'
$ vca nat add --type SNAT --original_ip 192.168.10.2 --translated_ip 23.92.245.228
Traceback (most recent call last):
  File "/home/achirko/workspace/vcloud/venv/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==6', 'console_scripts', 'vca')()
  File "/home/achirko/workspace/vcloud/venv/local/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/home/achirko/workspace/vcloud/venv/local/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/home/achirko/workspace/vcloud/venv/local/lib/python2.7/site-packages/click/core.py", line 936, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/achirko/workspace/vcloud/venv/local/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/achirko/workspace/vcloud/venv/local/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/home/achirko/workspace/vcloud/vca-cli/vca_cli/vca_cli.py", line 679, in nat
    gateways = vca.get_gateways(vdc)
  File "/home/achirko/workspace/vcloud/pyvcloud/pyvcloud/vcloudair.py", line 400, in get_gateways
    link = filter(lambda link: link.get_rel() == "edgeGateways", self.get_vdc(vdc_name).get_Link())
AttributeError: 'NoneType' object has no attribute 'get_Link'

**Comment by pacogomez** [comment]
this is probably due to the fact that a valid virtual data center (vdc) has not been selected yet. Use the command: 'vca vdc' to list vdcs and then 'vca vdc use --vdc myvdc' to select the vdc, then you will be able to use nat commands. we'll make this more robust in the next update
