### ISSUE TITLE
Depoying VM's with manual allocation mode

### ISSUE THREAD

**Issue by jackalsh** [vmware/pyvcloud#205]
**Version**: 
  * VCloud Director 9
  * pyvcloud 19.1.1

I want to deploy VApp with given IP.
My goal is to run **instantiate_vapp**(or similar) with **ip_allocation_mode = manual** so I will be able to set custom IP addresses to VM's.
Currently this is not seems to be supported. I can pass pool and dhcp, but static or manual are not supported.
How can this be done? Do pycloud library supports this?

Thank you for your support.

**Comment by gwesterfieldjr** [comment]
@jackalsh , I have implemented the change to support this as well as setting your own network adapter type. I will submit PR shortly

**Comment by hodgesrm** [comment]
Thanks @gwesterfieldjr.  I'll review the PR as soon as you submit it.

**Comment by hodgesrm** [comment]
@jackalsh, PR is in.  If you can install from pyvcloud master you should be able to check @gwesterfieldjr's change.  

`pip3 install git+https://github.com/vmware/pyvcloud` will get you the latest and greatest from git.

**Comment by Cylindric** [comment]
I have tried deploying a VM with a manual NIC allocation, but that fails after the VM is deployed, leaving an error in my vCloud.

Here's the commands I run to build the VM:

```
vm_name='sample-vm3'
spec = {
    'source_vm_name': 'redhat_7.4_1.0',
    'vapp': source_vapp_resource
}
spec['target_vm_name'] = vm_name
spec['hostname'] = vm_name
spec['network'] = 'my_network_name'
spec['ip_allocation_mode'] = 'manual'  # pool|dhcp|manual
spec['ip_address'] = '192.168.100.100'
spec['storage_profile'] = vdc.get_storage_profile('TIER2-Any')
vms = [spec]

# Build the VM
task = vapp.add_vms(
    specs=vms,
    deploy=True,
    power_on=True,
    all_eulas_accepted=True
)
result = client.get_task_monitor().wait_for_success(
    task=task,
    timeout=30,
    poll_frequency=1
)
```

This is the error I get after the VM is deployed:

```
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 563, in wait_for_success
    callback=callback)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 611, in wait_for_status
    raise VcdTaskException(task_status, task.Error)
pyvcloud.vcd.exceptions.VcdTaskException: VcdTaskException; 500/INTERNAL_SERVER_ERROR: error ([ 0aa6c3fa-39f3-491e-ae10-9ea39bbe8715 ] class java.lang.NullPointerException)
```

I have also tried by deploying with the default NIC, then deleting it, and trying to add a nic with the new settings:

```
task = vm.add_nic(
    adapter_type=NetworkAdapterType.VMXNET3.value,
    is_primary=True,
    is_connected=True,
    network_name='my_network_name',
    ip_address_mode=IpAddressMode.NONE.value,
    ip_address='192.168.100.100'
)
```

```
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/vm.py", line 450, in add_nic
    EntityType.NETWORK_CONNECTION_SECTION.value, net_conn_section)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1192, in put_linked_resource
    media_type)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1176, in put_resource
    params=params)
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 976, in _do_request
    _objectify_response(response, objectify_results))
  File "/opt/rh/rh-python36/root/usr/lib/python3.6/site-packages/pyvcloud/vcd/client.py", line 1013, in _response_code_to_exception
    raise InternalServerException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.InternalServerException: Status code: 500/INTERNAL_SERVER_ERROR, [ d2af0cc5-d616-4a76-8a98-1c8629e5325d ] No enum constant com.vmware.vcloud.api.rest.enums.IpAddressAllocationModeType.manual (request id: d2af0cc5-d616-4a76-8a98-1c8629e5325d)
```

**Comment by gwesterfieldjr** [comment]
I made the change to instantiate_vapp method in the VDC class which. It does not look like you are using the same implementation.

**Comment by kkkothari** [comment]
Hi,
Ip allocation mode supported values are pool, dhcp and manual.
