### ISSUE TITLE
Error during poweroff action

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvcloud#29]
I try to poweroff an existing vApp : 

```python
print("VAPP: %s" % vapp)
print("Poweroff vApp")
task_poweroff = vapp.poweroff()
task_poweroff_status = vca.block_until_completed(task_poweroff)
if task_poweroff_status is True:
    print("Poweron vApp")
    task_poweron = vapp.poweron()
    task_poweron_status = vca.block_until_completed(task_poweron)
    if task_poweron_status is True:
        print("vApp is ready")
```

The output : 

```bash
VAPP: <pyvcloud.vapp.VAPP object at 0x3dea910>
Poweroff vApp
unable to execute vApp operation: power:powerOff
Traceback (most recent call last):
  File "./test.py", line 151, in <module>
    test_lib()
  File "./test.py", line 142, in test_lib
    task_poweroff_status = vca.block_until_completed(task_poweroff)
  File "/home/vagrant/Apps/pyvcloud/pyvcloud/vcloudair.py", line 342, in block_until_completed
    progress = task.get_Progress()
AttributeError: 'bool' object has no attribute 'get_Progress'
`̀̀``

**Comment by pacogomez** [comment]
See https://github.com/vmware/pyvcloud/blob/master/tests/vcloud_tests.py#L467
This test passed. Let me know if you still have this issue with the latest version
