### ISSUE TITLE
Not able to login to ondemand (host=iam.vchs.vmware.com, version=5.7)

### ISSUE THREAD

**Issue by libowen9003** [vmware/pyvcloud#38]
I've been using them for a month and from yesterday I started to get a "HTTP/1.1 403 Forbidden" when doing the first login:
```
vca = VCA(host=host, username=username, service_type='ondemand',
          version='5.7', verify=True)
result = vca.login(password=password)
```
The debug is as below. /api/sc/instances gets a 403:
```
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.vchs.vmware.com
send: 'POST /api/iam/login HTTP/1.1\r\nHost: iam.vchs.vmware.com\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json;version=5.7\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-29-generic\r\nConnection: keep-alive\r\nAuthorization: Basic <...>\r\n\r\n'
reply: 'HTTP/1.1 201 Created\r\n'
header: Date: Tue, 07 Apr 2015 20:25:03 GMT
header: Via: 1.1 Repose (Repose/6.2.2.0)
header: Date: Tue, 07 Apr 2015 20:25:04 GMT
header: vchs-authorization: eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyZDNmOTE4NC1hMjUyLTRiODYtYTMzMy0xYTVkMWY0ZWY1ZWMiLCJzdWIiOiI5YjcxNzViYS1hYzgzLTRhYjgtOGJkOC1lNzg1NjZiOWMzN2IiLCJzY29wZSI6WyIyIiwiMyIsIm9wZW5pZCJdLCJjbGllbnRfaWQiOiJ2Y2hzX3NjIiwiZ3JhbnRfdHlwZSI6ImltcGxpY2l0IiwidXNlcl9pZCI6IjliNzE3NWJhLWFjODMtNGFiOC04YmQ4LWU3ODU2NmI5YzM3YiIsImVtYWlsIjoiYm93ZW4ubGlAYXZpbmV0d29ya3MuY29tIiwidXNlcl9uYW1lIjoiYm93ZW4ubGlAYXZpbmV0d29ya3MuY29tIiwiY29tcGFueV9pZCI6IjlkMjVkYzc0LTE2ZmQtNDQyNS1hOGUwLTE5Mzk2NDVjNzhjNCIsImNvbXBhbnlfbmFtZSI6Ik11cmFsaSBCYXNhdmFpYWgiLCJjdXN0b21lcl9udW1iZXIiOiIiLCJzZ19pZCI6WyI4ZjY1NjYxYS1kZTY5LTRkMjAtODBlMy1lZTAxZTUzMGM4NGIiLCIxNmU5MDEzNi04MmY0LTRmNjgtYjA3Yy0wOTQwNmIwODU4ODciXSwidmVyc2lvbiI6IjEuMCIsInBsYW5zIjpbXSwiaWF0IjoxNDI4NDM4MzA0LCJleHAiOjE0Mjg0MzkyMDQsImlzcyI6Imh0dHBzOi8vaWFtLnZjaHMudm13YXJlLmNvbS9vYXV0aC90b2tlbiIsImF1ZCI6WyJvcGVuaWQiXX0.FyEPFmPfjMxYEGlMqmYi-ecPuNn7-9oRS5mCx1-7fkZ767jLv8GCITEvQ04QYr7rkyUI00IBAmQHGSC9Vg5Ol1AOcaaBJqX9-TLbiFNeIZOBOYg5zO6NS2xNj0D3abVY3IdFT___pQdFov1y1xJXWhUC8o69Q_WUYRx4afKM6USP546k5SIuF-L4HkSG23oufs0IfB3KH0nIc_JmMs-zbbUKfAR3GANqJhfitUW1A5TLtLyIh5Tpq6Cq8JhggL6uimYDMCUFRwqibnNK1jrXMllBRHAULbA2n6PGg2GASMC_sZr3j4LgiDEaXQ60yQiEeonkiDqVwSwo0STB8Bzvnw
header: Content-Type: application/json; version=5.7
header: Content-Length: 99
header: Connection: close
header: Server: Jetty(9.2.z-SNAPSHOT)
DEBUG:requests.packages.urllib3.connectionpool:"POST /api/iam/login HTTP/1.1" 201 99
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): iam.vchs.vmware.com
send: 'GET /api/sc/instances HTTP/1.1\r\nHost: iam.vchs.vmware.com\r\nConnection: keep-alive\r\nAuthorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJqdGkiOiIyZDNmOTE4NC1hMjUyLTRiODYtYTMzMy0xYTVkMWY0ZWY1ZWMiLCJzdWIiOiI5YjcxNzViYS1hYzgzLTRhYjgtOGJkOC1lNzg1NjZiOWMzN2IiLCJzY29wZSI6WyIyIiwiMyIsIm9wZW5pZCJdLCJjbGllbnRfaWQiOiJ2Y2hzX3NjIiwiZ3JhbnRfdHlwZSI6ImltcGxpY2l0IiwidXNlcl9pZCI6IjliNzE3NWJhLWFjODMtNGFiOC04YmQ4LWU3ODU2NmI5YzM3YiIsImVtYWlsIjoiYm93ZW4ubGlAYXZpbmV0d29ya3MuY29tIiwidXNlcl9uYW1lIjoiYm93ZW4ubGlAYXZpbmV0d29ya3MuY29tIiwiY29tcGFueV9pZCI6IjlkMjVkYzc0LTE2ZmQtNDQyNS1hOGUwLTE5Mzk2NDVjNzhjNCIsImNvbXBhbnlfbmFtZSI6Ik11cmFsaSBCYXNhdmFpYWgiLCJjdXN0b21lcl9udW1iZXIiOiIiLCJzZ19pZCI6WyI4ZjY1NjYxYS1kZTY5LTRkMjAtODBlMy1lZTAxZTUzMGM4NGIiLCIxNmU5MDEzNi04MmY0LTRmNjgtYjA3Yy0wOTQwNmIwODU4ODciXSwidmVyc2lvbiI6IjEuMCIsInBsYW5zIjpbXSwiaWF0IjoxNDI4NDM4MzA0LCJleHAiOjE0Mjg0MzkyMDQsImlzcyI6Imh0dHBzOi8vaWFtLnZjaHMudm13YXJlLmNvbS9vYXV0aC90b2tlbiIsImF1ZCI6WyJvcGVuaWQiXX0.FyEPFmPfjMxYEGlMqmYi-ecPuNn7-9oRS5mCx1-7fkZ767jLv8GCITEvQ04QYr7rkyUI00IBAmQHGSC9Vg5Ol1AOcaaBJqX9-TLbiFNeIZOBOYg5zO6NS2xNj0D3abVY3IdFT___pQdFov1y1xJXWhUC8o69Q_WUYRx4afKM6USP546k5SIuF-L4HkSG23oufs0IfB3KH0nIc_JmMs-zbbUKfAR3GANqJhfitUW1A5TLtLyIh5Tpq6Cq8JhggL6uimYDMCUFRwqibnNK1jrXMllBRHAULbA2n6PGg2GASMC_sZr3j4LgiDEaXQ60yQiEeonkiDqVwSwo0STB8Bzvnw\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/json;version=5.7\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-29-generic\r\n\r\n'
reply: 'HTTP/1.1 403 Forbidden\r\n'
header: Date: Tue, 07 Apr 2015 20:25:04 GMT
header: X-Frame-Options: SAMEORIGIN
header: Via: 1.1 Repose (Repose/6.2.2.0)
header: Content-Length: 0
header: Connection: close
header: Server: Jetty(9.2.z-SNAPSHOT)
DEBUG:requests.packages.urllib3.connectionpool:"GET /api/sc/instances HTTP/1.1" 403 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aviuser/pyvcloud/pyvcloud/pyvcloud/vcloudair.py", line 117, in login
    self.instances = self.get_instances()
  File "/home/aviuser/pyvcloud/pyvcloud/pyvcloud/vcloudair.py", line 157, in get_instances
    if self.response.history[-1]:
IndexError: list index out of range
```

Do you know if it's a permission issue or something else? I updated the pyvcloud to the newest version and seems like it's still not working.

Thanks!

**Comment by pacogomez** [comment]
this might be a temporary issue. I'll keep you posted.

**Comment by pacogomez** [comment]
it is working now

**Comment by libowen9003** [comment]
Yes it's working now. Thanks!
