### ISSUE TITLE
issue with getting CPU and MEM 

### ISSUE THREAD

**Issue by 387119** [vmware/pyvcloud#463]
vCloud Director version: 8.20.0.6875354
doc: https://vmware.github.io/pyvcloud/pyvcloud.vcd.vm.html

example:
vm = VM(client, resource=vm_resource)
vm_mem=vm.get_memory()

Traceback (most recent call last):
  File "list-vcloud-all-resources.py", line 147, in <module>
    vm_mem=vm.get_memory()
  File "/opt/vcloud/pyvcloud/vcd/vm.py", line 111, in get_memory
    self.resource.VmSpecSection.MemoryResourceMb.Configured.text)
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}VmSpecSection

vm_cpu=vm.get_cpus()

Traceback (most recent call last):
  File "list-vcloud-all-resources.py", line 147, in <module>
    vm_cpus=vm.get_cpus()
  File "/opt/vcloud/pyvcloud/vcd/vm.py", line 97, in get_cpus
    int(self.resource.VmSpecSection.NumCpus.text),
  File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.__getattr__
  File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}VmSpecSection

for example other commands:
get_power_state & get_resources - work with no issues

state=vm.get_power_state()
print (state)
result: 4

**Comment by doug-baer** [comment]
bump. Confirmed that this is still an issue on vCD 9.1.0.7905680. I can't see anywhere that "VmSpecSection" is something available in the API, so I don't understand the reference to this here.

**Comment by pandeys** [comment]
VM.py has already methods get_cpus and get_memory. You can use these methods.

**Comment by 387119** [comment]
> VM.py has already methods get_cpus and get_memory. You can use these methods.

please read issue description, those method are not working.

**Comment by doug-baer** [comment]
this should not be closed. 
yes, there are methods. 
However, they do not return anything.

**Comment by doug-baer** [comment]
What are the prerequisites to making it work? I have not had this work against any of our clouds and see the same error as the original poster:

File "/opt/vcloud/pyvcloud/vcd/vm.py", line 97, in get_cpus
int(self.resource.VmSpecSection.NumCpus.text),
File "src/lxml/objectify.pyx", line 231, in lxml.objectify.ObjectifiedElement.getattr
File "src/lxml/objectify.pyx", line 451, in lxml.objectify._lookupChildOrRaise
AttributeError: no such child: {http://www.vmware.com/vcloud/v1.5}VmSpecSection

I ran out of time a few months ago when it would not work and I was unable to track down the source of the issue.
