### ISSUE TITLE
Creating Vapp with vm name have changed vapp name

### ISSUE THREAD

**Issue by kastesh** [vmware/pyvcloud#61]
I've used vca-cli, that uses pyvcloud.
I've created a vApp  from a template;  API version is  5.5.

This request is doing great:
```
vca vapp create --vapp test_vapp --catalog 'vms' --template 'template_name' --network 'network_name' --mode POOL --vdc vdc_name
```
But if I've added --vm vm_name, I get the error:
```
vca  vapp create --vapp test_vapp --vm vm_name --catalog 'vms' --template 'template_name' --network 'network_name' --mode POOL --vdc vdc_name
                   Traceback (most recent call last):
  File "/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==12', 'console_scripts', 'vca')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 705, in vapp
    vca.vcloud_session.get_vcloud_headers())
  File "/usr/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 2460, in display_progress
    sys.stdout.write("\r" + task_table(response.content) + '\n')
UnboundLocalError: local variable 'response' referenced before assignment
```
It is happen because, there is next condition in the pyvcloud code:
https://github.com/vmware/pyvcloud/blob/master/pyvcloud/vcloudair.py#L381
```
           if vm_name:
                if self.version == "5.5":
                   templateParams.set_name(vm_name)
                else:
                   gen_params = vcloudType.VmGeneralParamsType()
                   gen_params.set_Name(vm_name)
                   params.set_VmGeneralParams(gen_params)
```
This part is redefined name for created vApp. 
The situtation seems very odd, the vApp is created with name vm_name, not with name test_vapp.

**Comment by pacogomez** [comment]
upgrade vca-cli to 13rc4:

pip install vca-cli --pre --upgrade

**Comment by kastesh** [comment]
I'm very sorry. 

But we returned to bug with SourcedItem: https://github.com/vmware/pyvcloud/issues/41
If I skip --vm vm_name option, virtual host will create

```
vca --debug --insecure vapp create --vapp vapp_name --vm vm_name --catalog 'vms' --template 'cp-centos6' --network 'vdc_network' --mode POOL --vdc vdc_name

can't create the vApp, <?xml version="1.0" encoding="UTF-8"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" minorErrorCode="BAD_REQUEST" message="Bad request
 - Unexpected JAXB Exception
 - cvc-complex-type.2.4.a: Invalid content was found starting with element 'SourcedItem'. One of '{&quot;http://www.vmware.com/vcloud/v1.5&quot;:IsSourceDelete, &quot;http://www.vmware.com/vcloud/v1.5&quot;:SourcedVmInstantiationParams, &quot;http://www.vmware.com/vcloud/v1.5&quot;:AllEULAsAccepted}' is expected." majorErrorCode="400" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.vmware.com/vcloud/v1.5 http://XXX.XXX.XXX.XXX/api/v1.5/schema/master.xsd"></Error>
```

**Comment by lasko** [comment]
This is still an issue because vcloudair.py has the following:
```
        if ((self.version == "1.0") or (self.version == "1.5") or
           (self.version == "5.1") or (self.version == "5.5")):
            if vm_name or vm_cpus or vm_memory:
                params = vcloudType.SourcedVmInstantiationParamsType()
                params.set_Source(vcloudType.ReferenceType(href=vm_href))
                templateParams.add_SourcedItem(params)
                if vm_name:
                    pass
```

Its matching the version as 5.5 -- And in 5.5 you cannot have the add_SourcedItem() method since <SourcedItem> is not a valid tag in 5.5
