### ISSUE TITLE
Creating a VM from scratch with attached disk

### ISSUE THREAD

**Issue by bogdan-ds** [vmware/pyvcloud#642]
I'm bringing this up again, as I also want to add a disk upon VM creation similarly to how the VMs are created in vCloud Director. However I'm getting the 500 internal server error, which I'm not able to debug.

I also checked the definitions in the recomposeVApp API call, but couldn't find a definition of this section neither in the OVF spec nor in the API docs. Any help is appreciated, below is the debug:

```
Request uri (POST): https://10.10.71.12/api/vApp/vapp-cfdf2b11-d7a6-4385-8095-b30fe7f61f2b/action/recomposeVApp
Request headers: {'User-Agent': 'python-requests/2.22.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/*+xml;version=29.0', 'Connection': 'keep-alive', 'x-vcloud-authorization': '[REDACTED]', 'Content-Type': 'application/vnd.vmware.vcloud.recomposeVAppParams+xml', 'Content-Length': '1572'}
Request body: <RecomposeVAppParams xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" deploy="true" powerOn="true"><CreateItem name="created_disk_API"><Description/><GuestCustomizationSection><ovf:Info>Specifies Guest OS Customization Settings</ovf:Info><ComputerName>hostnameAPI</ComputerName></GuestCustomizationSection><NetworkConnectionSection><ovf:Info/><NetworkConnection network="VLAN10 Network"><NetworkConnectionIndex>1</NetworkConnectionIndex><IsConnected>true</IsConnected><IpAddressAllocationMode>DHCP</IpAddressAllocationMode></NetworkConnection></NetworkConnectionSection><VmSpecSection Modified="true"><ovf:Info>Virtual Machine specification</ovf:Info><OsType>vmwarePhoton64Guest</OsType><NumCpus>1</NumCpus><NumCoresPerSocket>1</NumCoresPerSocket><CpuResourceMhz><Configured>0</Configured></CpuResourceMhz><MemoryResourceMb><Configured>512</Configured></MemoryResourceMb><DiskSection><DiskSettings><DiskId>2000</DiskId><SizeMb>16384</SizeMb><UnitNumber>0</UnitNumber><BusNumber>0</BusNumber><AdapterType>5</AdapterType><ThinProvisioned>true</ThinProvisioned><StorageProfile href="https://10.10.71.12/api/vdcStorageProfile/23d190d1-d0bb-4fe2-b254-239e7505f944" name="*"/><iops>0</iops><VirtualQuantityUnit>byte</VirtualQuantityUnit></DiskSettings></DiskSection><HardwareVersion>vmx-14</HardwareVersion><VirtualCpuType>VM64</VirtualCpuType></VmSpecSection></CreateItem><AllEULAsAccepted>true</AllEULAsAccepted></RecomposeVAppParams>
Response status code: 500
Response headers: {'Date': 'Thu, 30 Jan 2020 07:10:35 GMT', 'X-VMWARE-VCLOUD-REQUEST-ID': 'a1ed2fce-3eb1-4908-adff-ff966d6dd2eb', 'x-vcloud-authorization': '[REDACTED]', 'Content-Type': 'application/vnd.vmware.vcloud.error+xml;version=29.0', 'X-VMWARE-VCLOUD-REQUEST-EXECUTION-TIME': '137', 'Transfer-Encoding': 'chunked'}
Response body: <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error xmlns="http://www.vmware.com/vcloud/v1.5" xmlns:ovf="http://schemas.dmtf.org/ovf/envelope/1" xmlns:vssd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_VirtualSystemSettingData" xmlns:common="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:rasd="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/CIM_ResourceAllocationSettingData" xmlns:vmw="http://www.vmware.com/schema/ovf" xmlns:ovfenv="http://schemas.dmtf.org/ovf/environment/1" xmlns:vmext="http://www.vmware.com/vcloud/extension/v1.5" xmlns:ns9="http://www.vmware.com/vcloud/versions" stackTrace="java.lang.NullPointerException	
at com.vmware.vcloud.api.rest.handlers.utils.ovfhandlers.VmSpecSectionHandler.toDisks(VmSpecSectionHandler.java:254)	
at com.vmware.vcloud.api.rest.handlers.utils.ovfhandlers.VmSpecSectionHandler.fillVmSpecFromOvfSection(VmSpecSectionHandler.java:209)	
at com.vmware.vcloud.api.rest.handlers.utils.ovfhandlers.VmSpecSectionHandler.fillVmSpecFromOvfSection(VmSpecSectionHandler.java:49)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.copyOvfSectionsToSpec(VAppUtils.java:1507)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.copyOvfSectionsToSpec(VAppUtils.java:1530)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.fillVmSpec(VAppUtils.java:1993)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.getVmSpec(VAppUtils.java:1981)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.lambda$populateComposeCreateItems$4(VAppUtils.java:2434)	
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)	
at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)	
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)	
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)	
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)	
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)	
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.populateComposeCreateItems(VAppUtils.java:2473)	
at com.vmware.vcloud.api.rest.handlers.utils.VAppUtils.createPlComposeVAppParams(VAppUtils.java:2383)	
at com.vmware.vcloud.api.rest.handlers.VAppHandler.recomposeVApp(VAppHandler.java:1237)	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)	
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)	
at java.lang.reflect.Method.invoke(Method.java:498)	
at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:180)	
at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:96)	
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:189)	
at com.vmware.vcloud.api.rest.jaxrs.ContextClassLoaderInvoker.invoke(ContextClassLoaderInvoker.java:27)	
at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)	
at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)	
at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)	
at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)	
at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)	
at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:262)	
at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)	
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)	
at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)	
at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:180)	
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:299)	
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:218)	
at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)	
at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:274)	
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)	
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)	
at com.vmware.vcloud.api.rest.diagnostics.DiagnosticFilter.doFilter(DiagnosticFilter.java:33)	
at com.vmware.vcloud.api.rest.diagnostics.RestApiDiagnosticsInterceptor.doFilter(RestApiDiagnosticsInterceptor.java:128)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.api.framework.web.ExtensibilityFilter.doFilter(ExtensibilityFilter.java:132)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.security.filters.ValidityExceptionFilter.doFilterHttp(ValidityExceptionFilter.java:47)	
at com.vmware.vcloud.security.filters.HttpFilterBean.doFilter(HttpFilterBean.java:35)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.security.web.RestSessionFilter.doFilter(RestSessionFilter.java:228)	
at com.vmware.vcloud.api.rest.diagnostics.RestApiDiagnosticsInterceptor.doFilter(RestApiDiagnosticsInterceptor.java:128)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.security.web.CellLivenessCheckFilter.doFilter(CellLivenessCheckFilter.java:54)	
at com.vmware.vcloud.api.rest.diagnostics.RestApiDiagnosticsInterceptor.doFilter(RestApiDiagnosticsInterceptor.java:128)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.api.rest.versioning.AcceptHeaderFilter.doFilter(AcceptHeaderFilter.java:109)	
at com.vmware.vcloud.api.rest.diagnostics.RestApiDiagnosticsInterceptor.doFilter(RestApiDiagnosticsInterceptor.java:128)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at com.vmware.vcloud.security.filters.ConversationFilter$1.run(ConversationFilter.java:39)	
at com.vmware.vcloud.security.filters.ConversationFilter$1.run(ConversationFilter.java:37)	
at com.vmware.vcloud.common.persist.ConversationContextExecutor.execute(ConversationContextExecutor.java:67)	
at com.vmware.vcloud.security.filters.ConversationFilter.doFilter(ConversationFilter.java:45)	
at com.vmware.vcloud.api.rest.diagnostics.RestApiDiagnosticsInterceptor.doFilter(RestApiDiagnosticsInterceptor.java:128)	
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)	
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)	
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)	
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:347)	
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:263)	
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)	
at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)	
at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:301)	
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)	
at com.vmware.vcloud.common.web.deployment.impl.RequestDiagnosticFilter.doFilter(RequestDiagnosticFilter.java:121)	
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)	
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)	
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)	
at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)	
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)	
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)	
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)	
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)	
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)	
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)	
at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)	
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)	
at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)	
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)	
at org.eclipse.jetty.server.Server.handle(Server.java:499)	
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)	
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)	
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)	
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)	
at com.vmware.vcloud.common.threading.ExtendedJettyQueuedThreadPool.runJob(ExtendedJettyQueuedThreadPool.java:33)	
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)	
at java.lang.Thread.run(Thread.java:748)	" majorErrorCode="500" message="[ a1ed2fce-3eb1-4908-adff-ff966d6dd2eb ] class java.lang.NullPointerException" minorErrorCode="INTERNAL_SERVER_ERROR"/>
```

PS I've added the disksection and disksettings to the add_vm_from_scratch method like that:

```
        vm_spec_section.append(E.DiskSection(
            E.DiskSettings(
                E.DiskId(2000),
                E.SizeMb(16384),
                E.UnitNumber(0),
                E.BusNumber(0),
                E.AdapterType(5),
                E.ThinProvisioned('true'),
                E.StorageProfile(href='https://10.10.71.12/api/vdcStorageProfile/23d190d1-d0bb-4fe2-b254-239e7505f944', name='*'),
                E.iops(0),
                E.VirtualQuantityUnit('byte')
            )
            ))
```

I also tried without a storage profile and some of the other elements. But getting the same error with the same stack trace.

**Comment by bogdan-ds** [comment]
Sorry, I managed to figure it out meanwhile, a proper DiskSection that worked for me was:

```
E.DiskSettings(
                E.SizeMb(16384),
                E.UnitNumber(0),
                E.BusNumber(0),
                E.AdapterType(5),
                E.ThinProvisioned('true'),
                E.overrideVmDefault('false')
            )
            ))
```
Closing...
