### ISSUE TITLE
README in 20.0.x incorrectly indicates that pyvcloud requires Python 3

### ISSUE THREAD

**Issue by dzolnierz** [vmware/pyvcloud#649]
After using version 20.0.3 in my project on Debian 9.12 (oldstable) the following exception is thrown:

```
Traceback (most recent call last):
  File "/usr/local/bin/vcloud-flexvolume", line 7, in <module>
    from flexvolume.attach import attach, waitforattach, isattached
  File "/usr/local/lib/python3.5/dist-packages/flexvolume/attach.py", line 19, in <module>
    from vcloud import client as Client, disk as Disk, vapp as VApp
  File "/usr/local/lib/python3.5/dist-packages/vcloud/client.py", line 12, in <module>
    from pyvcloud.vcd.vdc import VDC
  File "/usr/local/lib/python3.5/dist-packages/pyvcloud/vcd/vdc.py", line 35, in <module>
    from pyvcloud.vcd.metadata import Metadata
  File "/usr/local/lib/python3.5/dist-packages/pyvcloud/vcd/metadata.py", line 207
    f"{href}/{domain.value}/{key}"
                                 ^
SyntaxError: invalid syntax 
```

Debian oldstable has Python 3.5 and f-strings are introduced in Python 3.6. I've managed to fix it using future_fstrings. I can prepare PR on request.

**Comment by shashim22** [comment]
Hi,

Thanks for reporting this. 
README has got correction in version 20.1. 

-Shashi
