### ISSUE TITLE
[Help] method to modify a VDC

### ISSUE THREAD

**Issue by azzamsa** [vmware/pyvcloud#665]
I am working on a function to modify a VDC. Currently we only have `create_org_vdc`.

`create_org_vdc` consume an api from [POST /admin/org/{id}/vdcsparams](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/f27d65ea-c25b-45ed-9193-c8cc77507622/9a1f04e3-359b-4a19-9c62-7c0fafdfeac8/doc/doc/operations/POST-CreateVdcParams.html) with input type [CreateVdcParamsType](https://vdc-repo.vmware.com/vmwb-repository/dcr-public/f27d65ea-c25b-45ed-9193-c8cc77507622/9a1f04e3-359b-4a19-9c62-7c0fafdfeac8/doc/doc/types/CreateVdcParamsType.html). 

![image](https://user-images.githubusercontent.com/17734314/82984672-d3227280-a01c-11ea-83c2-c8199a0cd1a6.png)

Sadly `vdcparams` only availiable for `create` operation. Otherwise I could only (IMHO) modify some line in `create_org_vdc` to make a new function `update_org_vdc`, e.g:

- `self.client.post_linked_resource(` -> `self.client.put_linked_resource(`
- `RelationType.ADD` -> `RelationType.EDIT`

Now, the only way I have to modify a VDC is by using `PUT /admin/vdc/{id}`, which has a different input type: `AdminVdcType`.

Now I am stuck in creating `E.Vdc` object. because it has different requirement than `E.CreateVdcParams`. Mainly the:

- `E.MaxComputePolicy()`
- `E.DefaultComputePolicy()`

The docs says that both are not mandatory parameters:

![image](https://user-images.githubusercontent.com/17734314/82985162-ba668c80-a01d-11ea-9e27-98971d9ddb7b.png)

But unluckily I always get this error:

``` python
Traceback (most recent call last):
  File "coba_cpu.py", line 75, in <module>
    storage_profiles=storage_profiles,
  File "/home/user/code/pyvcloud/pyvcloud/vcd/org.py", line 1727, in update_org_vdc
    params)
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1389, in put_linked_resource
    media_type)
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1373, in put_resource
    params=params)
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1169, in _do_request
    _objectify_response(response, objectify_results))
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1174, in _response_code_to_exception
    raise BadRequestException(sc, request_id, objectify_response)
pyvcloud.vcd.exceptions.BadRequestException: Status code: 400/BAD_REQUEST, [ 0c1a27df-7aa7-4659-9336-1eb9ffe9e42d ] HTTP 400 Bad Request
 - cvc-complex-type.2.4.a: Invalid content was found starting with element 'VdcStorageProfile'. One of '{"http://www.vmware.com/vcloud/v1.5":VdcStorageProfiles, "http://www.vmware.com/vcloud/v1.5":DefaultComputePolicy, "http://www.vmware.com/vcloud/v1.5":MaxComputePolicy, "http://www.vmware.com/vcloud/v1.5":VCpuInMhz2}' is expected. (request id: 0c1a27df-7aa7-4659-9336-1eb9ffe9e42d)
```

Saying that I must supply those params.

I am stuck in *what to supply to those objects* (.eg where to get policy href). Because I don't find any other module is using `E.Vdc`

Any help would be greatly appreciated.

**Comment by azzamsa** [comment]
I tried several **MWE**, some of them:


### # 1
``` python
import requests
from pyvcloud.vcd.api_client import ApiClient
from pyvcloud.vcd.client import BasicLoginCredentials, E, EntityType

requests.packages.urllib3.disable_warnings()

# create client
host = "https://foo.net"
user = "mydevadmin"
org = "System"
passwd = "secret"

client = ApiClient(
    host, verify_ssl_certs=False, log_requests=True, log_bodies=True, log_headers=True,
)
creds = BasicLoginCredentials(user, org, passwd)
client.set_credentials(creds)


def update_vdc():
    vdc_href = f"{host}/api/admin/vdc/50910825-ab9c-41a1-b423-fake"
    vdc_resource = client.get_resource(vdc_href)

    vdc_resource["IsEnabled"] = E.IsEnabled(False)

    return client.put_resource(
        vdc_resource.get("href"), vdc_resource, EntityType.ADMIN.value,
    )


update_vdc()
```

But I get `UnsupportedMediaTypeException`

```python
Traceback (most recent call last):
  File "vdc.py", line 55, in <module>
    update_vdc()
  File "vdc.py", line 50, in update_vdc
    return client.put_resource(
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1377, in put_resource
    params=params)
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1173, in _do_request
    _objectify_response(response, objectify_results))
  File "/home/user/code/pyvcloud/pyvcloud/vcd/client.py", line 1203, in _response_code_to_exception
    objectify_response)
pyvcloud.vcd.exceptions.UnsupportedMediaTypeException: Status code: 415/UNSUPPORTED_MEDIA_TYPE, Unsupported Media Type (request id: 6dac001d-2986-45a1)
````

I will try other workaround and update the result here.

**Comment by azzamsa** [comment]
related: https://github.com/vmware/pyvcloud/issues/515

**Comment by azzamsa** [comment]
**Solved** after digging the code in `client` module.

use `none` in `media_type`

MWE:

```python
import requests
from pyvcloud.vcd.api_client import ApiClient
from pyvcloud.vcd.client import BasicLoginCredentials, E

requests.packages.urllib3.disable_warnings()

# create client
host = "https://foo.net"
user = "mydevadmin"
org = "System"
passwd = "secret"

client = ApiClient(
    host, verify_ssl_certs=False, log_requests=True, log_bodies=True, log_headers=True,
)
creds = BasicLoginCredentials(user, org, passwd)
client.set_credentials(creds)

vdc_href = f"{host}/api/admin/vdc/50910825-ab9c-41a1-b423-fake"


def update_vdc():
    vdc_resource = client.get_resource(vdc_href)

    vdc_resource["IsEnabled"] = E.IsEnabled(False)
    return client.put_resource(vdc_resource.get("href"), vdc_resource, None,)


update_vdc()

```
