### ISSUE TITLE
pyvcloud.vcd.exceptions.EntityNotFoundException: Network 'vAppNet-vAppNet-vApp_Network' not found in the Virtual Datacenter

### ISSUE THREAD

**Issue by Prasaddiwalkar** [vmware/pyvcloud#759]
```
Traceback (most recent call last):
  File "D:/workdir/PythonTraining/test/mywinrm.py", line 25, in <module>
    task = vdc.instantiate_vapp("my-vapp", "DEV_Public", "catalogvm",
  File "C:\Users\deshpapr\AppData\Roaming\Python\Python38\site-packages\pyvcloud\vcd\vdc.py", line 280, in instantiate_vapp
    raise EntityNotFoundException(
pyvcloud.vcd.exceptions.EntityNotFoundException: Network 'vAppNet-vAppNet-vApp_Network' not found in the Virtual Datacenter.

```

**Comment by ricardoqs** [comment]
Same happens to me when I upgraded to pyvcloud version 23.0.1 exception is raised in vdc.py line 338
``` python
# Check if networks used in vapp template are found in vDC
        for net in template_vdc_networks:
            if net not in vdc_networks:
                raise EntityNotFoundException(
                    'Network \'%s\' not found in the Virtual Datacenter.' %
                    net)
```
the vAppTemplate network is under NAT and does not exist at a VDC level.

This issue didn't exist on version 23.0.0

**Comment by vogash** [comment]
> Same happens to me with a natRouted network in the template. The network is configured on the vApp and therefore doesn't exist on the vDC level. Had to downgrade to 23.0.0 as a workaround.

after downgrade we started to get `Error: Catalog not found (or) Access to resource is forbidden`
