### ISSUE TITLE
VCD none for vCloudDirector

### ISSUE THREAD

**Issue by nlamirault** [vmware/pyvcloud#8]
With this code, i've got a VCD empty : 

```python
def test_lib():
    vca = vcloudair.VCA()
    vca.login(host, '%s@%s' % (user, org), password, None, 'vcd', '5.1')
    vcd = vca.get_vCloudDirector()
    print "VCD : %s" % vcd
    print "Catalog"
    for catalog in vcd.list_catalogs():
        print catalog
    print "Templates"
    for templates in vcd.list_templates({'--catalog': False}):
        print templates
        # print "[template]: %s" % template.__dict__
    print "Networks:"
    for networks in vcd.get_networkRefs():
        print networks.__dict__

if __name__ == '__main__':
    test_lib()
```

```bash
$ ./test.py 
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.myhost
send: 'POST /api/sessions HTTP/1.1\r\nHost: api.myhost\r\nContent-Length: 0\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/*+xml;version=5.1\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-30-generic\r\nConnection: keep-alive\r\nAuthorization: Basic bmxhbWlyYXVsdC5vYWJARkNBX09BQjAxOkZUbGFuaV8zMw==\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 16 Jan 2015 11:56:11 GMT
header: x-vcloud-authorization: PnmR24poQkLcMYyGqkye9JJkSDCT4gwFifHiZfxTg+k=
header: Set-Cookie: vcloud-token=PnmR24poQkLcMYyGqkye9JJkSDCT4gwFifHiZfxTg+k=; Secure; Path=/
header: Content-Type: application/vnd.vmware.vcloud.session+xml;version=5.1
header: Date: Fri, 16 Jan 2015 11:56:12 GMT
header: Content-Length: 1454
header: Connection: close
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.myhost
send: 'GET /api/org/19adf4a6-942d-4048-a36c-09a68161f0e9 HTTP/1.1\r\nHost: api.myhost\r\nConnection: keep-alive\r\nx-vcloud-authorization: PnmR24poQkLcMYyGqkye9JJkSDCT4gwFifHiZfxTg+k=\r\nAccept-Encoding: gzip, deflate\r\nAccept: application/*+xml;version=5.1\r\nUser-Agent: python-requests/2.4.3 CPython/2.7.6 Linux/3.13.0-30-generic\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Date: Fri, 16 Jan 2015 11:56:12 GMT
header: Date: Fri, 16 Jan 2015 11:56:12 GMT
header: Content-Type: application/vnd.vmware.vcloud.org+xml;version=5.1
header: Content-Encoding: gzip
header: Connection: close
VCD : None
Catalog
Traceback (most recent call last):
  File "./test.py", line 187, in <module>
    test_lib()
  File "./test.py", line 158, in test_lib
    for catalog in vcd.list_catalogs():
AttributeError: 'NoneType' object has no attribute 'list_catalogs'
```

**Comment by nlamirault** [comment]
Sorry for noise. With your comment on issue #3 it works. Could you update documentat ion with this : 
```python
vca = vcloudair.VCA()
vca.login(host, '%s@%s' % (user, org), password, None, 'vcd', '5.1')
for datacenter in vca.get_vdcReferences():
    print datacenter.name
vcd = vca.get_vCloudDirector(vdcId='FCA_OAB01_VDC02')
print "VCD : %s" % vcd
```

thanks.

**Comment by pacogomez** [comment]
thanks
