### ISSUE TITLE
Assumes at least one edge gateway exists: Can't login; list index out of range

### ISSUE THREAD

**Issue by ckamps** [vmware/pyvcloud#85]
Symptoms and proposed fix are documented in the following issue within the `vca-cli` project:

https://github.com/vmware/vca-cli/issues/30

In addition to the can't login issue, here's another failure example that helped point us in the right direction:

```python
(cloudify)[root@localhost yum.repos.d]# vca --insecure vdc use --vdc devcloud
/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:730: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html (This warning will only appear once by default.)
  InsecureRequestWarning)
Using vdc 'devcloud' in profile 'default'
Traceback (most recent call last):
  File "/etc/yum.repos.d/cloudify/bin/vca", line 9, in <module>
    load_entry_point('vca-cli==1.1', 'console_scripts', 'vca')()
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/vca_cli/vca_cli.py", line 322, in vdc
    print_vdc_details(ctx, the_vdc, vca.get_gateways(vdc))
  File "/etc/yum.repos.d/cloudify/lib/python2.7/site-packages/pyvcloud/vcloudair.py", line 400, in get_gateways
    response = requests.get(link[0].get_href(), headers=self.vcloud_session.get_vcloud_headers(), verify=self.verify)
IndexError: list index out of range
```

**Comment by ckamps** [comment]
Here's the fix as copied from the `vca-cli` issue:

With the help of Yoram of Gigaspaces, we tracked down one cause of this error to the `pyvcloud` library assuming that at least one gateway always exists. In our case, we have zero gateways.

See the following section in `pyvcloud/vcloudair.py` where we added this line:

```python
if not link: return gateways
```
So that when `link` is empty, the ensuing code does not try to use it.

```python
def get_gateways(self, vdc_name):
    """
    Request a list of the Gateways within a Virtual Data Center.
 
    :param vdc_name: (str): The virtual data center name.
    :return: (list of Gateway)  A list of :class:`.pyvcloud.gateway.Gateway` objects describing the available gateways
 
    **service type:** ondemand, subscription, vcd
    """
    gateways = []
    vdc = self.get_vdc(vdc_name)
    if not vdc: return gateways
    link = filter(lambda link: link.get_rel() == "edgeGateways", vdc.get_Link())
    if not link: return gateways
    self.response = Http.get(link[0].get_href(), headers=self.vcloud_session.get_vcloud_headers(), verify=self.verify, logger=self.logger)
    if self.response.status_code == requests.codes.ok:
    ...
```

**Comment by pacogomez** [comment]
thanks @yoramw @ckamps, will include this fix in pyvcloud v16
